# fly.toml app configuration file generated for alura-linguagens-leeomarques on 2023-04-20T14:19:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alura-linguagens-leeomarques"
primary_region = "gig"

[build]
  image = "leomarques/linguagensapi:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
